// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "@/components/providers/providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Providers>
          {children}
        </Providers>

        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js" async />
      </body>
    </html>
  );
}
