// import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "@/components/providers/providers";
import Header from "@/components/organism/header/Header";
import Image from "next/image";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Suspense>{children}</Suspense>
        </Providers>

        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js" async />
      </body>
    </html>
  );
}
